on:
  - push
  - pull_request
jobs:
  compile_sketch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/compile-sketches@v1
        with:
          fqbn: arduino:avr:nano
          sketch-paths: Arduino/SelfomatController
          libraries: Adafruit\ NeoPixel@1.10.6
